
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--- LOAD CHARACTERS ---
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET IDENTITY_INSERT [api].[Characters] ON 
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (1, N'01', N'Inox Brute', N'Inox', N'Brute', N'Brute', 0, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (2, N'02', N'Quatryl Tinkerer', N'Quatryl', N'Tinkerer', N'Tinkerer', 0, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (3, N'03', N'Orchid Spellweaver', N'Orchid', N'Spellweaver', N'Spellweaver', 0, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (4, N'04', N'Human Scoundrel', N'Human', N'Scoundrel', N'Scoundrel', 0, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (5, N'05', N'Savvas Cragheart', N'Savvas', N'Cragheart', N'Cragheart', 0, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (6, N'06', N'Vermling Mindthief', N'Vermling', N'Mindthief', N'Mindthief', 0, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (7, N'07', N'Valrath Sunkeeper', N'Valrath', N'Sunkeeper', N'Sun', 1, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (8, N'08', N'Valrath Quartermaster', N'Valrath', N'Quartermaster', N'Three Spears', 1, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (9, N'09', N'Aesther Summoner', N'Aesther', N'Summoner', N'Concentric Circles', 1, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (10, N'10', N'Aesther Nightshroud', N'Aesther', N'Nightshroud', N'Moon/Eclipse', 1, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (11, N'11', N'Harrower Plagueherald', N'Harrower', N'Plagueherald', N'Cthulu', 1, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (12, N'12', N'Inox Berserker', N'Inox', N'Berserker', N'Lightning Bolt', 1, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (13, N'13', N'Quatryl Soothsinger', N'Quatryl', N'Soothsinger', N'Music Note', 1, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (14, N'14', N'Orchid Doomstalker', N'Orchid', N'Doomstalker', N'Spiky/Angry Face', 1, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (15, N'15', N'Human Sawbones', N'Human', N'Sawbones', N'Saw', 1, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (16, N'16', N'Savvas Elementalist', N'Savvas', N'Elementalist', N'Triforce', 1, 1, 0)
INSERT [api].[Characters] ([CharacterId], [CharacterNumber], [FullName], [Race], [Class], [SpoilerFreeName], [IsSpoiler], [IsOfficial], [IsExtended]) VALUES (17, N'17', N'Vermling Beast Tyrant', N'Vermling', N'Beast Tyrant', N'Two-Mini', 1, 1, 0)
SET IDENTITY_INSERT [api].[Characters] OFF

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--- LOAD CITY EVENTS ---
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Execute api.LoadEventCard 'City', '1', 'You decide to unwind at the Sleeping Lion, but just as you are starting to relax, a bear of a man crashes into your table, scattering your drinks across the floor.
Towering over him is a massive Inox. ""What did you say about my horns?"" the Inox shouts.
The man stands up and brushes shards of glass from his tunic. ""I said the sight of them makes me want to vomit!""
The Inox roars and charges headlong into the man, crashing through more tables in the process. At this, the entire tavern erupts into violence. After all, when a man is deep into his drink, the last thing you want to do is knock that drink over.', 'A', 'Join the fray! These insults will not go unanswered!', 'Nothing like busting some drunken skulls to lift one''s spirits. It tuns out to be a great way to unwind. Unfortunately, the proprietor of the Sleeping Lion doesn''t exactly see it that way, and he sullenly asks for compensation for the damage you caused.', 'Return to Deck', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gain 10 experience each.', 'Either lose 5 gold each or lose 1 reputation.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B', 'Do your best to stop the fighting. This is a respectable establishment.', 'After restraining the enraged Inox and offering to replace the drinks of a few of the more belligerent patrons, you calm the place down a bit. Some of the non-human patrons are understandably on edge, but the proprietor thanks you for your efforts and reimburses you for the drinks.', 'Return to Deck', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gain 1 reputation.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
Execute api.LoadEventCard 'City', '2', 'As the daylight fades, you find yourselves wandering through a half-crowded market street, browsing wares.
""Hey! Over here!"" You turn in the direction of the voice to see a filthy Vermling gesturing from a dark alley. ""Yeah, you grim-looking chaps. I have something you might be interested in.""
The Vermling holds out a piece of metal covered in sludge. ""Found this in the sewer. Writing on it I don''t understand, but I know it''s valuable. You can have it for ten gold!""', 'A', 'Pay for the thing. You never know.', 'You hand over the gold and take hold of the piece of garbage. Amidst troubling brown smears you see a lot of meaningless scratches likely made by rates and bugs. Oh well. Sometimes the long shot doesn''t pay off.', 'Return to Deck', 'Text', 'Pay 10 collective gold.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No effect.', NULL, NULL, '""Bah! You don''t have enough. Come back when you do!""', 'Return to Deck', 'Text', 'Otherwise', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No effect.', NULL, NULL, 'B', 'Refuse to pay. Never trust a Vermling.', 'You laugh and gesture the Vermling away. You can recognize a low-life swindler when you see one. And that piece of garbage was just…foul.', 'Return to Deck', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No effect.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
Execute api.LoadEventCard 'City', '3', 'As the daylight fades, you find yourselves wandering through a half-crowded market street, browsing wares.
""Hey! Over here!"" You turn in the direction a of the voice to see a filthy Vermling gesturing from a dark alley. ""Yeah, you grim-looking chaps. I have something you might be interested in.""
The Vermling holds out a piece of metal covered in sludge. ""Found this in the sewer. Writing on it l don''t understand, but I know its valuable. You can have it for ten gold!""', 'A', 'Pay for the thing. You never know.', 'You hand over the gold and take hold of the metal. You wipe off the grime and slop to discover a foreign contraption made of large gears and many moving parts. If you can figure out what it is, this device might actually be of some worth.', 'Remove from Game', 'Text', 'Pay 10 collective gold.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gain 1 collective ""Curious Gear"" (Item 125).', 'Global Achievement: ""Ancient Technology.""', NULL, '""Bah! You don''t have enough. Come back when you do!""', 'Return to Deck', 'Text', 'Otherwise', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No effect.', NULL, NULL, 'B', 'Refuse to pay. Never trust a Vermling.', 'You laugh and gesture the Vermling away. You can recognize a low-life swindler when you see one. And that piece of garbage was just…foul.', 'Return to Deck', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No effect.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
Execute api.LoadEventCard 'City', '4', 'Having recently returned from your latest adventure, you are approached by a ratty-looking boy in tears.
""Please, sirs, could you please help me with my cat? He went over there, and I’m afraid."" The boy points a dirty finger at a decrepit, abandoned building. ""I don''t know what else to do.""', 'A', 'Find a cat? You have more important things to do.', 'You shake your head and direct the boy to go find his mother. With any luck she will knock some sense into him so that he stops troubling strangers with such trivial matters.', 'Remove from Game', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No effect.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B', 'Reassure the boy and go find the cat.', 'You approach the foreboding house full of heroic bravado. There''s certainly nothing otherworldly about the structure, but its fallen beams and piles of rubble do make it difficult to look around. By the time you find the cat hiding under a burned-out bed frame, you are utterly exhausted. At least they boy is ecstatic his cat has been found.', 'Remove from Game', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Lose 1 ✓ each.', 'Gain 1 reputation.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
Execute api.LoadEventCard 'City', '5', 'After resting for the evening, you start out your day noticing a great number of prominent, commanding posters around the city.
Reading one, you learn that the Sanctuary of the Great Oak is laying down the foundation for a new building on the east side of Gloomhaven. Everyone is encouraged to come and help. This could be an important community event.', 'A', 'Go help lay the foundation.', 'Amidst a great deal of revelry, you put all you have into laying the foundation of the sanctuary. Surely much good will be done here healing the sick and wounded. After all your exhausting efforts, though, you might end up being their first patients.', 'Remove from Game', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Lose 1 ✓.', 'Gain 1 reputation.', 'Gain 1 prosperity.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B', 'Take the opportunity to steal some valuables in the area while people are distracted.', 'You head to the prosperous east side of town, not to help lay down the foundation, but to steal some goods from shopkeepers too silly to lock up there wares during the festivities. You make off with a good deal of money and the distracted guards are none the wiser.', 'Remove from Game', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gain 5 gold each.', 'Reputation < -4: Gain 5 additional gold each.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
Execute api.LoadEventCard 'City', '6', 'You awake in the middle of the night to the sound of alarms ringing in the west. You recognize them as the warning clangs of an attack on the wall.
Any force bold enough to assault the defenses of Gloomhaven can''t be good. Fore a moment you are grateful for the prolific number of guards defending the city. But still, there is always the possibility that the guards may not be enough.', 'A', 'Go aid in the defense of the city.', 'You rush towards the West Gate, eager to fight back the invaders. As you approach, you see a mass of Vermlings climbing over the wall and attacking the guards with daggers and arrows. You yell and charge into the battle. Is a rough fight, but you emerge victorious, covered in fur and blood. The citizens of Gloomhaven remain safe, and the town is free to grow and prosper.', 'Remove from Game', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gain 5 experience each.', 'Gain 1 prosperity.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B', 'If the guards are distracted by an attacking force, now would be the perfect time to steal some valuables.', 'The town erupts into chaos with panicked cries of ""Vermlings!"" - a perfect opportunity to collect some valuables. Slinking around to an abandoned shop, you find a way in and pilfer the safe. In the morning, the devastation from the assault is noticeable. Downtrodden looks greet you as you pass, and you wonder if your presence was missed along the walls.', 'Remove from Game', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gain Random Item Design.', 'Reputation < 4: Lose 1 reputation.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
Execute api.LoadEventCard 'City', '7', 'Occasionally your dealings in town lead you past the building docks. All conversation gets drowned out by the constant din of loading and unloading cargo and crew. This makes it all the more surprising when you hear a voice above the noise directed straight at you.
""Oi! You with the hard looks and big arms! I desperately need some help o''er here! Spare a few minutes to help make sure I get out of port on time? Otherwise I''ll be stuck here until tomorrow!""', 'A', 'Help the captain load his ship.', 'What was advertised as a few minutes turns out to be an hour or two as you lug large crates full of some foul-smelling liquid from a nearby warehouse into the hold of the ship. At lease the captain is relieved that he''ll be able to set sail on time, though. He gratefully pays you, but you can''t help but think that such menial labor might be beneath you.', 'Remove from Game', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gain 5 gold each.', 'Reputation > 9: Lose 1 reputation.', 'Reputation < -4: Gain 1 reputation.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B', 'Move on with your business. You don''t have the time or inclination for such things.', 'Unwilling to be bothered by such trivial matters, you continue on your way amidst curses from the ship''s captain. ""Blast it all! You''ll get nowhere in life with that sort of attitude!""', 'Remove from Game', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Reputation > 4: Gain 1 reputation.', 'Reputation < -9: Lose 1 reputation.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
Execute api.LoadEventCard 'City', '8', 'On a trip to the New Market, you see a curious sea chart prominently displayed in a Valrath merchant''s stall.
""Ah, I see this interests you!"" he says while holding it up, taking great care not to damage it. ""I''ve been told this map will lead you to a location of untold riches! Wondrous beyond anything you have seen before!""
The Valrath gestures grandly with his free hand and his smile grows wide. ""How can you say no to this? Just make me an offer.""', 'A', 'The map does look valuable. Decide to bargain for it.', 'After some amount of haggling back and forth, you settle on a price and pay for the map. You recognize some of the landmarks and should be able to find this place of ""untold treasure"" by hiring a ship.', 'Remove from Game', 'Text', 'Pay 20 (reputation < 10) or 15 (reputation > 9) collective gold.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Unlock ""Sunken Vessel"" (93) (N-17).', 'Party Achievement: ""A Map to Treasure""', NULL, 'Despite your valiant efforts, you cannot get the merchant to lower his price to something you can afford.', 'Return to Deck', 'Text', 'Otherwise', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No effect.', NULL, NULL, 'B', 'Refuse to deal with the merchant.', 'Wary of the merchant''s overly exuberant nature, you politely decline his offer and go about your intended business.', 'Remove from Game', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No effect.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
Execute api.LoadEventCard 'City', '25', 'On a trip to the Coin District, you catch sight of an old, wiry Valrath carrying a large, intricate vase out of his front door.
As you get closer, the Valrath begins to struggle with the vase, sweat pouring from his brow. Under the strain, the Valrath loses his balance, and the fragile vase topples downward as he yells a string of curses.', 'A', 'Attempt to catch the vase.', 'You race forward and wrap your arms around the vase. You manage to keep grip of it, preventing tragedy. The Valrath is relieved and offers to pay you for your trouble if you carry it the rest of the way.', 'Remove from Game', 'Character', NULL, 1, 'Character', NULL, 5, 'Character', NULL, 12, 'Gain collective 5 gold.', NULL, NULL, 'You race forward and attempt to catch the vase, but it is too much for you. Your grip loosens and the vase shatters into a hundred pieces. The Valrath is irate, demanding compensation from you for breaking it. You pay him what you can.', 'Remove from Game', 'Text', 'Otherwise', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Lose collective 10 gold.', NULL, NULL, 'B', 'With no time to react, watch the vase fall to the ground.', 'You watch helplessly as the vase careens out of the Valrath''s grasp and, once it connects with the hard ground, shatters into a hundred pieces. The Valrath looks distraught and a little angry. You exchange a sympathetic glance with him and then continue about your business.', 'Remove from Game', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No effect.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--- LOAD CHARACTERS ---
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET IDENTITY_INSERT [api].[BattleGoals] ON 
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (1, N'458', N'Streamliner', N'Have five or more total cards in your hand and discard at the end of the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (2, N'459', N'Layabout', N'Gain 7 or fewer experience points during the scenario.', 2, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (3, N'460', N'Workhorse', N'Gain 13 or more experience points during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (4, N'461', N'Zealot', N'Have three or fewer total cards in your hand and discard at the end of the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (5, N'462', N'Masochist', N'Your current hit point value must be equal or less than 2 at the end of the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (6, N'463', N'Fast Healer', N'Your current hit point value must be equal to your maximum hit point value at the end of the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (7, N'464', N'Neutralizer', N'Cause a trap to be sprung or disarmed on your turn or on the turn of one of your summons during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (8, N'465', N'Plunderer', N'Loot a treasure overlay tile during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (9, N'466', N'Protector', N'Allow none of your character allies to become exhausted during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (10, N'467', N'Explorer', N'Reveal a room tile by opening a door on your turn during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (11, N'468', N'Hoarder', N'Loot five or more money tokens during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (12, N'469', N'Indigent', N'Loot no money tokens or treasure overlay titles during this scenario.', 2, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (13, N'470', N'Pacifist', N'Kill three or less monsters during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (14, N'471', N'Sadist', N'Kill five or more monsters during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (15, N'472', N'Hunter', N'Kill one or more elite monsters during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (16, N'473', N'Professional', N'Use your equipped items a number of times equal to greater than your level plus 2 during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (17, N'474', N'Aggressor', N'Have one or more monsters present on the map at the beginning of every round during this scenario.', 2, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (18, N'475', N'Dynamo', N'Kill a monster during the scenario by causing at least 4 more points of damage to it more than necessary.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (19, N'476', N'Purist', N'Use no items during the scenario.', 2, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (20, N'477', N'Opener', N'Be the first to kill a monster during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (21, N'478', N'Diehard', N'Never allow your current hit point value to drop below half your maximum hit point value (rounded up) during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (22, N'479', N'Executioner', N'Kill an undamaged monster with a single attack during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (23, N'480', N'Straggler', N'Take only long rests during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (24, N'481', N'Scrambler', N'Take only short rests during the scenario.', 1, N'Gloomhaven', 1, 0)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (25, 'SE-001', N'Acrobatic', N'Lose a card to negate 5 or more damage.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (26, 'SE-002', N'Ambusher', N'Open a door and end your move action adjacent to a monster in the revealed room.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (27, 'SE-003', N'Assassin', N'Kill a monster before it takes any actions in the scenario.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (28, 'SE-004', N'Assistant', N'Kill a monster attacked by an ally earlier in the round.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (29, 'SE-005', N'Bastion', N'Be adjacent to at least two monsters while standing on a door hex.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (30, 'SE-006', N'Bully', N'Kill a monster afflicted by a negative condition.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (31, 'SE-007', N'Contagious', N'While afflicted by a negative condition, apply any negative condition to a monster.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (32, 'SE-008', N'Covetous', N'Never collect a money token from end-of-turn looting.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (33, 'SE-009', N'Cuddler', N'Take a rest only on rounds in which an ally is also taking a long or short rest.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (34, 'SE-010', N'Discriminating', N'Kill no elite monsters or bosses during the scenario.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (35, 'SE-011', N'Distracted', N'Kill a monster you are not adjacent to while adjacent to another monster.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (36, 'SE-012', N'Drowsy', N'Declare a long rest while at your maximum hit point value.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (37, 'SE-013', N'Elitist', N'Kill only elite monsters.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (38, 'SE-014', N'Exterminator', N'Kill three monsters in the same round.', 2, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (39, 'SE-015', N'Fearful', N'Never end your turn adjacent to a monster.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (40, 'SE-016', N'Feeble', N'Be the first player to become exhausted.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (41, 'SE-017', N'Feral', N'Have the most cards in your lost pile at the end of the scenario.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (42, 'SE-018', N'Finisher', N'Kill the last monster to die in the scenario.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (43, 'SE-019', N'Hesitant', N'Never go first in a round''s initiative.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (44, 'SE-020', N'Hothead', N'Add two cards to your lost pile before your first rest.', 2, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (45, 'SE-021', N'Instigator', N'Except when long resting, never go last in a round''s initiative.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (46, 'SE-022', N'Insulting', N'Apply another negative condition to a monster already afflicted by one.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (47, 'SE-023', N'Limping', N'Move using only basic move actions.', 2, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (48, 'SE-024', N'Lucky', N'Kill a monster with an attack with disadvantage.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (49, 'SE-025', N'Marksman', N'Kill a monster three or more hexes away from you.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (50, 'SE-026', N'Miser', N'Never exit a room while money tokens remain in it.', 2, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (51, 'SE-027', N'Mugger', N'Kill a monster and loot its money token on the same turn.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (52, 'SE-028', N'Multitasker', N'Kill a monster and open a door on the same round.', 2, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (53, 'SE-029', N'Paranoid', N'End each of your turns adjacent to a wall or obstacle.', 2, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (54, 'SE-030', N'Peacemonger', N'Never deal the killing blow to a monster.', 2, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (55, 'SE-031', N'Perforated', N'Lose 6 or more hit points in a single round.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (56, 'SE-032', N'Pickpocket', N'Perform a loot action while adjacent to at least two monsters.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (57, 'SE-033', N'Pincushion', N'Get attacked by three or more monsters in the same round.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (58, 'SE-034', N'Prosperous', N'Collect three or more money tokens in the same turn.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (59, 'SE-035', N'Ravager', N'Play two cards for their lost actions on the same turn.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (60, 'SE-036', N'Recluse', N'Never end your turn adjacent to an ally.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (61, 'SE-037', N'Reserved', N'Have the fewest cards in your lost pile at the end of the scenario.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (62, 'SE-038', N'Restless', N'Move at least one hex on each of your turns (except when long resting).', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (63, 'SE-039', N'Retaliator', N'Don''t make any attacks in the scenario until after you''ve taken damage for the first time.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (64, 'SE-040', N'Ritualistic', N'Kill a monster when two or more elements are strong or waning.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (65, 'SE-041', N'Scavenger', N'Collect more money tokens than any other player.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (66, 'SE-042', N'Shadow', N'End each of your turns adjacent to an ally.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (67, 'SE-043', N'Sharpshooter', N'Kill a monster in a different room (neither of you may be on a doorway tile).', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (68, 'SE-044', N'Slayer', N'Kill two monsters in the same round.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (69, 'SE-045', N'Sleepless', N'Take damage during the same round you take a long rest.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (70, 'SE-046', N'Sober', N'Use no potions during the scenario.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (71, 'SE-047', N'Sociable', N'Never leave a room with a character ally remaining in it.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (72, 'SE-048', N'Specialized', N'Don''t use any basic actions.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (73, 'SE-040', N'Stalwart', N'Never leave a hex adjacent to a monster.', 2, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (74, 'SE-050', N'Stubborn', N'Do not lose any cards to negate damage during the scenario.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (75, 'SE-051', N'Thorough', N'Never exit a room with monsters remaining in it.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (76, 'SE-052', N'Untouchable', N'Take no damage.', 2, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (77, 'SE-053', N'Wasteful', N'Lose a card to negate 2 or less damage from an attack.', 1, N'Satire''s Extended Battle Goals', 0, 1)
INSERT [api].[BattleGoals] ([BattleGoalId], [CardNumber], [GoalName], [GoalDescription], [Reward], [Source], [IsOfficial], [IsExtended]) VALUES (78, 'SE-054', N'Winded', N'Never have fewer than one card in your hand.', 1, N'Satire''s Extended Battle Goals', 0, 1)
SET IDENTITY_INSERT [api].[BattleGoals] OFF
GO
