CREATE TABLE [dbo].[EventCardLoad] (
    [EventType]                     NVARCHAR (16)  NULL,
    [CardNumber]                    VARCHAR (16)   NULL,
    [Situation]                     NVARCHAR (MAX) NULL,
    [OptionLetter_A]                NVARCHAR (1)   NULL,
    [OptionDescription_A]           NVARCHAR (MAX) NULL,
    [Result_A_1]                    NVARCHAR (MAX) NULL,
    [CardDestiny_A_1]               NVARCHAR (16)  NULL,
    [RequirementType_A_1_Q1]        NVARCHAR (8)   NULL,
    [RequirementDescription_A_1_Q1] NVARCHAR (32)  NULL,
    [CharacterID_A_1_Q1]            BIGINT         NULL,
    [RequirementType_A_1_Q2]        NVARCHAR (8)   NULL,
    [RequirementDescription_A_1_Q2] NVARCHAR (32)  NULL,
    [CharacterID_A_1_Q2]            BIGINT         NULL,
    [RequirementType_A_1_Q3]        NVARCHAR (8)   NULL,
    [RequirementDescription_A_1_Q3] NVARCHAR (32)  NULL,
    [CharacterID_A_1_Q3]            BIGINT         NULL,
    [Reward_A_1_W1]                 NVARCHAR (128) NULL,
    [Reward_A_1_W2]                 NVARCHAR (128) NULL,
    [Reward_A_1_W3]                 NVARCHAR (128) NULL,
    [Result_A_2]                    NVARCHAR (MAX) NULL,
    [CardDestiny_A_2]               NVARCHAR (16)  NULL,
    [RequirementType_A_2_Q1]        NVARCHAR (8)   NULL,
    [RequirementDescription_A_2_Q1] NVARCHAR (32)  NULL,
    [CharacterID_A_2_Q1]            BIGINT         NULL,
    [RequirementType_A_2_Q2]        NVARCHAR (8)   NULL,
    [RequirementDescription_A_2_Q2] NVARCHAR (32)  NULL,
    [CharacterID_A_2_Q2]            BIGINT         NULL,
    [RequirementType_A_2_Q3]        NVARCHAR (8)   NULL,
    [RequirementDescription_A_2_Q3] NVARCHAR (32)  NULL,
    [CharacterID_A_2_Q3]            BIGINT         NULL,
    [Reward_A_2_W1]                 NVARCHAR (128) NULL,
    [Reward_A_2_W2]                 NVARCHAR (128) NULL,
    [Reward_A_2_W3]                 NVARCHAR (128) NULL,
    [OptionLetter_B]                NVARCHAR (1)   NULL,
    [OptionDescription_B]           NVARCHAR (MAX) NULL,
    [Result_B_1]                    NVARCHAR (MAX) NULL,
    [CardDestiny_B_1]               NVARCHAR (16)  NULL,
    [RequirementType_B_1_Q1]        NVARCHAR (8)   NULL,
    [RequirementDescription_B_1_Q1] NVARCHAR (32)  NULL,
    [CharacterID_B_1_Q1]            BIGINT         NULL,
    [RequirementType_B_1_Q2]        NVARCHAR (8)   NULL,
    [RequirementDescription_B_1_Q2] NVARCHAR (32)  NULL,
    [CharacterID_B_1_Q2]            BIGINT         NULL,
    [RequirementType_B_1_Q3]        NVARCHAR (8)   NULL,
    [RequirementDescription_B_1_Q3] NVARCHAR (32)  NULL,
    [CharacterID_B_1_Q3]            BIGINT         NULL,
    [Reward_B_1_W1]                 NVARCHAR (128) NULL,
    [Reward_B_1_W2]                 NVARCHAR (128) NULL,
    [Reward_B_1_W3]                 NVARCHAR (128) NULL,
    [Result_B_2]                    NVARCHAR (MAX) NULL,
    [CardDestiny_B_2]               NVARCHAR (16)  NULL,
    [RequirementType_B_2_Q1]        NVARCHAR (8)   NULL,
    [RequirementDescription_B_2_Q1] NVARCHAR (32)  NULL,
    [CharacterID_B_2_Q1]            BIGINT         NULL,
    [RequirementType_B_2_Q2]        NVARCHAR (8)   NULL,
    [RequirementDescription_B_2_Q2] NVARCHAR (32)  NULL,
    [CharacterID_B_2_Q2]            BIGINT         NULL,
    [RequirementType_B_2_Q3]        NVARCHAR (8)   NULL,
    [RequirementDescription_B_2_Q3] NVARCHAR (32)  NULL,
    [CharacterID_B_2_Q3]            BIGINT         NULL,
    [Reward_B_2_W1]                 NVARCHAR (128) NULL,
    [Reward_B_2_W2]                 NVARCHAR (128) NULL,
    [Reward_B_2_W3]                 NVARCHAR (128) NULL
);

